Adjustments for core notification and icon changes
piwik/plugin-LogViewer pull request #73
Opened 2023-08-07 03:00 UTC by bx80

### Description:

This PR updates the UI test screenshots affected by the notification and icon updates in core PR [#21077](https://github.com/matomo-org/matomo/pull/21077)

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-08-07 13:43 UTC, michalkleiner requested changes

2023-08-07 13:43 UTC, michalkleiner commented on tests/UI/expected-ui-screenshots/LogViewer_filter_date.png
Missing styling completely.

2023-08-07 13:43 UTC, michalkleiner commented on tests/UI/expected-ui-screenshots/LogViewer_filter_severity.png
Missing styling completely.

2023-08-07 13:43 UTC, michalkleiner commented on tests/UI/expected-ui-screenshots/LogViewer_info_no_supported_writer.png
It seems like the action icons next to the "Use regular expressions" checkbox needs a bit of a tweak around their alignment, is there perhaps a custom CSS applied?

2023-08-16 00:10 UTC, bx80 commented on tests/UI/expected-ui-screenshots/LogViewer_filter_date.png
This is a randomly failing tests which has been like this for quite a while, it's nothing to do with the changes in this PR.

2023-08-16 00:11 UTC, bx80 commented on tests/UI/expected-ui-screenshots/LogViewer_filter_severity.png
Also a randomly failing test unrelated to these changes.

2023-08-16 09:28 UTC, michalkleiner commented on tests/UI/expected-ui-screenshots/LogViewer_filter_date.png
Yep, that's fine, but I guess we shouldn't commit new screenshots that are from a failed test?

2023-08-16 14:30 UTC, merged